package com.novel.writing.assistant.service

import com.novel.writing.assistant.model.GenerationRequest
import com.novel.writing.assistant.model.GenerationResponse
import io.ktor.client.*
import io.ktor.client.engine.okhttp.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.util.*

@Serializable
data class CozeRequest(
    val prompt: String,
    val model: String = "coze-v1"
)

@Serializable
data class CozeResponse(
    val id: String,
    val choices: List<CozeChoice>
)

@Serializable
data class CozeChoice(
    val text: String
)

object GenerationService {
    private val httpClient = HttpClient(OkHttp)
    private const val COZE_API_URL = "https://api.coze.cn/v1/chat/completions"
    private val COZE_API_KEY = System.getenv("COZE_API_KEY") ?: ""
    
    suspend fun generateContent(request: GenerationRequest): GenerationResponse {
        val startTime = System.currentTimeMillis()

        val sessionId = if (request.isContinueWriting) {
            request.sessionId?.takeIf { it.isNotBlank() }
                ?: throw MissingSessionIdException()
        } else {
            UUID.randomUUID().toString()
        }
        
        LogService.info("Generating content for project ${request.projectId}, type: ${if (request.isContinueWriting) "continuation" else "initial"}")
        
        val outputContent = try {
            if (request.isContinueWriting) {
                generateContinuation(request, sessionId)
            } else {
                generateInitial(request)
            }
        } catch (e: Exception) {
            if (e is MissingSessionIdException || e is NoContextException) {
                throw e
            }
            // Handle exception with error reporting
            ErrorHandlingService.handleException(
                e = e,
                context = mapOf(
                    "projectId" to request.projectId,
                    "generationType" to if (request.isContinueWriting) "continuation" else "initial"
                )
            )
            
            // Fallback to mock response if API call fails
            if (request.isContinueWriting) {
                "This is a mock continuation of your writing. In production, this would be generated by Coze API based on your saved context."
            } else {
                "This is a mock initial generation. In production, this would be generated by Coze API based on your genre type and writing direction."
            }
        }
        
        val duration = System.currentTimeMillis() - startTime
        val generationType = if (request.isContinueWriting) "continuation" else "initial"
        
        val response = GenerationResponse(
            id = UUID.randomUUID().toString(),
            projectId = request.projectId,
            sessionId = sessionId,
            generationType = generationType,
            outputContent = outputContent,
            generationDate = Date().toString(),
            duration = duration
        )
        
        // Save to history
        try {
            HistoryService.saveHistory(
                projectId = request.projectId,
                generationType = generationType,
                inputParams = request.toString(),
                outputContent = outputContent,
                duration = duration
            )
            if (!request.genreType.isNullOrBlank()) {
                ContextService.saveContext(
                    projectId = request.projectId,
                    sessionId = sessionId,
                    contextType = "genre",
                    contextContent = request.genreType
                )
            }
            if (!request.writingDirection.isNullOrBlank()) {
                ContextService.saveContext(
                    projectId = request.projectId,
                    sessionId = sessionId,
                    contextType = "writing_direction",
                    contextContent = request.writingDirection
                )
            }
            val chapterTitle = buildChapterTitle(request.projectId, sessionId)
            ContextService.saveContext(
                projectId = request.projectId,
                sessionId = sessionId,
                contextType = "chapter_title",
                contextContent = chapterTitle
            )
            val chapterSummary = buildChapterSummaryFallback(outputContent)
            ContextService.saveContext(
                projectId = request.projectId,
                sessionId = sessionId,
                contextType = "chapter_summary",
                contextContent = chapterSummary
            )
            if (generationType == "initial") {
                ContextService.saveContext(
                    projectId = request.projectId,
                    sessionId = sessionId,
                    contextType = "outline",
                    contextContent = buildOutlineFallback(request)
                )
                ContextService.saveContext(
                    projectId = request.projectId,
                    sessionId = sessionId,
                    contextType = "characters",
                    contextContent = buildCharactersFallback(request)
                )
                ContextService.saveContext(
                    projectId = request.projectId,
                    sessionId = sessionId,
                    contextType = "world",
                    contextContent = buildWorldFallback()
                )
                ContextService.saveContext(
                    projectId = request.projectId,
                    sessionId = sessionId,
                    contextType = "plot_outline",
                    contextContent = buildPlotOutlineFallback(request)
                )
            }
            ContextService.saveContext(
                projectId = request.projectId,
                sessionId = sessionId,
                contextType = "chapter",
                contextContent = outputContent
            )
            LogService.info("Content generated successfully for project ${request.projectId}, duration: ${duration}ms")
        } catch (e: Exception) {
            ErrorHandlingService.handleException(
                e = e,
                context = mapOf(
                    "projectId" to request.projectId,
                    "operation" to "saveHistoryAndContext"
                )
            )
        }
        
        return response
    }
    
    private suspend fun generateInitial(request: GenerationRequest): String {
        val prompt = buildString {
            append("请根据以下要求生成小说内容：\n")
            append("题材类型：${request.genreType ?: "小说"}\n")
            if (request.writingDirection != null) {
                append("写作方向：${request.writingDirection}\n")
            }
            if (request.referenceFileId != null) {
                // In production, we would read the reference document content
                append("参考文档：已提供参考文档\n")
            }
            append("\n请生成一段符合要求的小说内容。")
        }
        
        return callCozeApi(prompt)
    }
    
    private suspend fun generateContinuation(request: GenerationRequest, sessionId: String): String {
        val lastChapterContent = ContextService.getLatestContextContent(request.projectId, sessionId, "chapter")
        val genreType = ContextService.getLatestContextContent(request.projectId, sessionId, "genre")
        val writingDirection = ContextService.getLatestContextContent(request.projectId, sessionId, "writing_direction")
        val chapterTitle = ContextService.getLatestContextContent(request.projectId, sessionId, "chapter_title")
        val outline = ContextService.getLatestContextContent(request.projectId, sessionId, "outline")
        val characters = ContextService.getLatestContextContent(request.projectId, sessionId, "characters")
        val world = ContextService.getLatestContextContent(request.projectId, sessionId, "world")
        val plotOutline = ContextService.getLatestContextContent(request.projectId, sessionId, "plot_outline")
        val chapterSummary = ContextService.getLatestContextContent(request.projectId, sessionId, "chapter_summary")

        if (lastChapterContent.isNullOrBlank() && outline.isNullOrBlank() && characters.isNullOrBlank() &&
            world.isNullOrBlank() && plotOutline.isNullOrBlank() && chapterSummary.isNullOrBlank()
        ) {
            throw NoContextException()
        }

        val prompt = buildString {
            append("请基于已保存的写作上下文继续写作：\n")
            if (!genreType.isNullOrBlank()) append("题材：$genreType\n")
            if (!writingDirection.isNullOrBlank()) append("写作方向：$writingDirection\n")
            if (!chapterTitle.isNullOrBlank()) append("章节名称：$chapterTitle\n")
            if (!outline.isNullOrBlank()) append("大纲：$outline\n")
            if (!characters.isNullOrBlank()) append("人物设定：$characters\n")
            if (!world.isNullOrBlank()) append("世界观：$world\n")
            if (!plotOutline.isNullOrBlank()) append("剧情大纲：$plotOutline\n")
            if (!chapterSummary.isNullOrBlank()) append("章节梗概：$chapterSummary\n")
            if (!lastChapterContent.isNullOrBlank()) append("上一章节内容：$lastChapterContent\n")
            append("\n请继续写作，保持风格一致，延续情节并避免重复。")
        }
        
        return callCozeApi(prompt)
    }
    
    private suspend fun callCozeApi(prompt: String): String {
        if (COZE_API_KEY.isBlank()) {
            throw IllegalStateException("COZE_API_KEY is not set")
        }
        val cozeRequest = CozeRequest(prompt = prompt)
        
        val response = httpClient.post(COZE_API_URL) {
            headers {
                append(HttpHeaders.Authorization, "Bearer $COZE_API_KEY")
                append(HttpHeaders.ContentType, ContentType.Application.Json.toString())
            }
            setBody(Json.encodeToString(cozeRequest))
        }
        
        val responseBody = response.bodyAsText()
        val cozeResponse = Json.decodeFromString<CozeResponse>(responseBody)
        
        return cozeResponse.choices.firstOrNull()?.text ?: "生成内容失败"
    }

    private fun buildChapterTitle(projectId: String, sessionId: String): String {
        val nextChapterNumber = ContextService.getNextChapterNumber(projectId, sessionId)
        return "第${nextChapterNumber}章"
    }

    private fun buildChapterSummary(content: String, maxLength: Int = 200): String {
        val normalized = content.replace("\r\n", "\n").trim()
        if (normalized.length <= maxLength) return normalized
        return normalized.take(maxLength)
    }

    private fun buildOutlineFallback(request: GenerationRequest): String {
        val genre = request.genreType ?: "小说"
        val direction = request.writingDirection ?: ""
        return if (direction.isBlank()) {
            "题材：$genre\n主线：从开篇到高潮再到结尾的完整故事线"
        } else {
            "题材：$genre\n主线：$direction"
        }
    }

    private fun buildCharactersFallback(request: GenerationRequest): String {
        val direction = request.writingDirection ?: ""
        return if (direction.isBlank()) {
            "主角：未命名（可在后续补充）\n配角：未命名（可在后续补充）\n动机：待补充"
        } else {
            "主角：围绕“$direction”的核心人物\n配角：推动冲突与转折的关键人物\n动机：与写作方向一致"
        }
    }

    private fun buildWorldFallback(): String {
        return "世界观：现代都市（可在后续改为架空/历史/科幻等）"
    }

    private fun buildPlotOutlineFallback(request: GenerationRequest): String {
        val direction = request.writingDirection ?: ""
        return if (direction.isBlank()) {
            "剧情大纲：引子—冲突—升级—高潮—收束"
        } else {
            "剧情大纲：围绕“$direction”推进（引子—冲突—升级—高潮—收束）"
        }
    }

    private fun buildChapterSummaryFallback(content: String): String {
        return buildChapterSummary(content)
    }
}
